# Generated by Django 4.2.7 on 2025-06-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.TextField()),
                ("foreign_url", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
                ("reviewed", models.BooleanField(default=False)),
                ("ocr", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TranslatedSentance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentance", models.TextField()),
                ("sefaria_ref", models.CharField(max_length=100)),
                ("is_translated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("he", "Hebrew"),
                            ("ru", "Russian"),
                            ("ua", "Ukrainian"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "sentance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.translatedsentance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sefaria_ref", models.CharField(max_length=100)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.page"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoundingContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sefaria_ref", models.CharField(max_length=100)),
                ("top", models.CharField(max_length=50)),
                ("left", models.CharField(max_length=50)),
                ("height", models.CharField(max_length=50)),
                ("width", models.CharField(max_length=50)),
                (
                    "page_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.page"
                    ),
                ),
            ],
        ),
    ]
